project:
  type: website
  output-dir: docs
  resources: assets/presentations/pesonen_probAI2022_slides

website:
  title: "Henri Pesonen's homepage"
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - presentations.qmd
      - icon: github
        href: http://github.com/hpesonen
      - icon: globe
        href: https://bsky.app/profile/hpesonen.bsky.social

format:
  html:
    theme: simplex
    css: styles.css
