project:
  type: website
  resources: assets/presentations/pesonen_probAI2022_slides

website:
  title: "Henri Pesonen's homepage"
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - presentations.qmd
      - icon: github
        href: http://github.com/hpesonen
      - icon: twitter
        href: https://twitter.com/henri_pesonen

format:
  html:
    theme: simplex
    css: styles.css
