---
title: "Publications"
---



Journal
=======

- Kičiatovas, D., Guo, Q., Kailas, M., **Pesonen, H.**, Corander, J., Kaski, S., Pitkänen, E. and Mustonen, V. (2022) [Identification of multiplicatively acting modulatory mutational signatures in cancer.](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-022-05060-8) BMC Bioinformatics 23, 522 (2022). https://doi.org/10.1186/s12859-022-05060-8

- **Pesonen, H.**, Simola, U., Köhn-Luque, A., Vuollekoski, H., Lai, X., Frigessi, A., Kaski, S., Frazier, D.T.,  Maneesoonthorn, W., Martin, G.M. and Corander, J. (2022) [ABC of the Future](https://onlinelibrary.wiley.com/doi/full/10.1111/insr.12522). International Statistical Review. 2022.

-  Aushev, A., **Pesonen, H.**, Heinonen, M., Corander, J. and Kaski S. (2020) [Likelihood-Free Inference with Deep Gaussian Processes](https://www.sciencedirect.com/science/article/pii/S0167947322001098) *Computational Statistics \& Data Analysis*, 2022, 174:107529 

- Pöntinen, A.K. et al. (2021), [Apparent nosocomial adaptation of Enterococcus faecalis predates the modern hospital era](https://www.nature.com/articles/s41467-021-21749-5) *Nature Communications* 2021, 12(1):1-13

- Arstila, V., Georgescu, A.L., **Pesonen, H.**, Lunn, D., Noreika, V. and Falter-Wagner, C.M. (2020) [Event timing in human vision: Modulating factors and independent functions](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0226122) *PloS one* 2020, 15(8):e0226122.

- Kataja, E.-L., Karlsson, L., Leppänen, J.M., Pelto, J., Häikiö, T., Nolvi, S., **Pesonen, H.**, Parsons, C.E., Hyönä, J. and Karlsson, H. (2020) [Maternal depressive symptoms during the pre‐and postnatal periods and infant attention to emotional faces](https://srcd.onlinelibrary.wiley.com/doi/abs/10.1111/cdev.13152)
*Child development* 2020, 91(2):e475-e480

- Sikka, P., **Pesonen, H.** and Revonsuo, A. (2018) [Peace of mind and anxiety in the waking state are related to the affective content of dreams](https://www.nature.com/articles/s41598-018-30721-1) *Scientific reports* 2018, 8(1):1-13

- Salokangas, R.K.R, Schultze-Lutter, F., Schmidt, S.J., **Pesonen, H.**, Luutonen, S.,  Patterson, P., von Reventlow, H.G., Heinimaa, M., From, T. and Hietala, J., (2020) [Childhood physical abuse and emotional neglect are specifically associated with adult mental disorders](https://www.tandfonline.com/doi/10.1080/09638237.2018.1521940) *Journal of Mental Health* 2020, 29(4):376-384

- Kallionpää, R.E., Pesonen, H.,  Scheinin, A. Sandman, N., Laitio, R., Scheinin, H., Revonsuo, A. and Valli, K. (2019) [Single-subject analysis of N400 event-related potential component with five different methods](https://www.sciencedirect.com/science/article/pii/S0167876019300406)
*International Journal of Psychophysiology* 2019, 144:14-24

- Korhonen, L.S., Kortesluoma, S., Lukkarinen, M., Peltola, V., **Pesonen, H.**, Pelto, J., Tuulari, J.J., Lukkarinen, H., Vuorinen, T., Karlsson, H. and Karlsson, L. (2019) [Prenatal maternal distress associates with a blunted cortisol response in rhinovirus-positive infants](https://www.sciencedirect.com/science/article/pii/S0306453018310722) *Psychoneuroendocrinology* 2019, 107:187-190

- Kataja, E.-L., Karlsson, L., Parsons, C.E., Pelto, J., **Pesonen, H.**, Häikiö, T., Hyönä, J., Nolvi, S., Korja, R. and Karlsson H. (2019) [Maternal pre-and postnatal anxiety symptoms and infant attention disengagement from emotional faces](https://www.sciencedirect.com/science/article/abs/pii/S0165032718312837)
*Journal of affective disorders*, 2019, 243:280-289

- Kokko, J., Remes, U., Thomas, O., **Pesonen, H.** and Corander, J. (2019) [PYLFIRE: Python implementation of likelihood-free inference by ratio estimation](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7041362.1/) *Wellcome Open research* 2019, 4:197

- Nolvi, S., Uusitupa, H.‐M., Bridgett, D.J., **Pesonen, H.**, Aatsinki, A.‐K. Kataja, E.‐L., Korja, R., Karlsson, H. and Karlsson, L. (2018) [Human milk cortisol concentration predicts experimentally induced infant fear reactivity: moderation by infant sex](https://onlinelibrary.wiley.com/doi/abs/10.1111/desc.12625) *Developmental Science* 2018, 21(4):e12625

- Nolvi, S., Bridgett, D.J., **Pesonen, H.**, Korja, R., Kataja, E.‐L., Karlsson, H. and Karlsson, L. (2018)
[Infant sex moderates the effects of maternal pre‐and postnatal stress on executive functioning at 8 months of age](https://onlinelibrary.wiley.com/doi/abs/10.1111/infa.12206) *Infancy* 2018, 23(2):194-210

- Railo, H., Tuominen, J., Kaasinen, V. and **Pesonen, H.** (2017) [Dynamic changes in cortical effective connectivity underlie transsaccadic integration in humans](https://academic.oup.com/cercor/article/27/7/3609/3056384) *Cerebral Cortex* 2017, 27(7):3609-3617

- Railo, H., Karhu, V.-M., Mast, J., **Pesonen, H.** and Koivisto, M. (2016) [Rapid and accurate processing of multiple objects in briefly presented scenes](https://jov.arvojournals.org/article.aspx?articleid=2491178) *Journal of Vision* 2016, 16(3):8

- Pesonen, M., **Pesonen, H.** and Nevalainen, J. (2015) [Covariance matrix estimation for left-censored data](https://www.sciencedirect.com/science/article/abs/pii/S0167947315001437), *Computational Statistics & Data Analysis*, 2015, 92:13-25

- Aatsinki, A.-K., Uusitupa, H.-M., Munukka, E., **Pesonen, H.**, Rintala, A., Pietilä, S., Lahti, L., Eerola, E., Karlsson, L. and Karlsson, H. (2018) [Gut microbiota composition in mid-pregnancy is associated with gestational weight gain but not prepregnancy body mass index](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6205042/) *Journal of Women's Health*, 2018, 27(10):1293-1301

- **Pesonen, H** (2011)., [A framework for Bayesian receiver autonomous integrity monitoring in urban navigation](https://onlinelibrary.wiley.com/doi/abs/10.1002/j.2161-4296.2011.tb02583.x) *Navigation*, 2011, 58(3):229-240

Preprints
==========

- Pöntinen, A. K. (equal contr.), Gladstone, R. A. (equal contr.), *Pesonen, H.* (equal contr.), Pesonen, M., Cléon, F., Parcell, B. J., Kallonen, T., Simonsen, G. S., Croucher, N. J., McNally, A., Parkhill, J., Johnsen, P. J., Samuelsen, Ø., Corander, J. (2023), [Β-lactam antibiotic use modulates multi-drug resistant clone success in Escherichia coli populations: a longitudinal multi-country genomic cohort study.](http://ssrn.com/abstract=4364886) Lancet preprint.

- Mikkola, P., Martin, O. A., Chandramouli, S., Hartmann, M., Pla, O. A., Thomas, O., **Pesonen, H.**, Corander, J., Vehtari, A., Kaski, S., Bürkner, P.-C. and Klami, A. (2021) [Prior knowledge elicitation: The past, present, and future](https://arxiv.org/abs/2112.01380)

- Aushev, A., Tran, T., **Pesonen, H.**, Howes, A. and Kaski, S. (2021) [Likelihood-Free Inference in State-Space Models with Unknown Dynamics](https://arxiv.org/abs/2111.01555)

- Thomas, O., **Pesonen, H.**, Sá-Leão, R., de Lencastre, H., Kaski, S. and Corander, J. (2020) [Split-BOLFI for for misspecification-robust likelihood free inference in high dimensions](https://arxiv.org/abs/2002.09377)

- Thomas, O., **Pesonen, H.** and Corander, J. (2020) [Generalised Bayes Updates with f-divergences through Probabilistic Classifiers](https://arxiv.org/abs/2007.04358)

- Thomas, O., **Pesonen, H.** and Corander, J. (2020) [Probabilistic elicitation of expert knowledge through assessment of computer simulations](https://arxiv.org/abs/2002.10902)

Conference
==========

- Discussant at panel "Probabilistic Programming" at BayesComp2023, Kittilä, Finland
    - Moderator: Aki Vehtari (Aalto University, Finland)
    - Mitzi Morris (Columbia University, USA)
    - Junpeng Lao (Google, Switzerland)
    - Tor Fjelde (Turing.jl / Cambridge University, United Kingdom) 
    - **Henri Pesonen** (ELFI / Oslo University Hospital, Norway)

- **Pesonen, H.** and Piché, R. (2011) Bayesian positioning using Gaussian mixture models with time-varying component weights [pdf](https://www.researchgate.net/profile/Robert_Piche/publication/259193183_Bayesian_positioning_using_Gaussian_mixture_models_with_time-varying_component_weights/links/0046352a59df58f815000000/Bayesian-positioning-using-Gaussian-mixture-models-with-time-varying-component-weights.pdf) *JSM*, 2011

- **Pesonen, H.** and Piché, R. (2010) [Cubature-based Kalman filters for positioning](https://ieeexplore.ieee.org/abstract/document/5653829)
*7th Workshop on Positioning, Navigation and Communication*, 2010, 45-49

Thesis
======

**Pesonen, H** (2013), [Bayesian Estimation and Quality Monitoring for Personal Positioning Systems](https://trepo.tuni.fi/handle/10024/114878)

Lecture materials
=================

- [Todennäköisyyslaskennan peruskurssi](assets/lecture_materials/TILM3553.pdf)
- [Tilastollisen päättelyn peruskurssi](assets/lecture_materials/TILM3555.pdf)
- [Tilastollisia malleja](assets/lecture_materials/TILM3511.pdf)

